[package]
name = "competitions"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.stellar-aid]
versioning = "semver"
storage-schema = 1
min-compatible = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bench]]
name = "competitions_benchmark"
path = "benches/competitions_benchmark.rs"
harness = false

[dependencies]
soroban-sdk.workspace = true
shared = { path = "../shared", version = "0.1.0" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
default = []
testutils = ["soroban-sdk/testutils"]
