#!/usr/bin/env bash
# verify_deployment.sh — Master post-deployment validation orchestrator.
#
# Runs all validation sub-scripts, collects their exit codes, and writes a
# timestamped Markdown report to the reports/ directory.
#
# Usage:
#   ./scripts/verify_deployment.sh [network] [contracts_file] [--report-dir DIR]
#
# Defaults:
#   network        = testnet
#   contracts_file = config/${network}_contracts.json
#   report-dir     = reports/verify
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETWORK="${1:-testnet}"
CONTRACTS_FILE=""
REPORT_DIR="reports/verify"

# Parse arguments
for arg in "$@"; do
  case "$arg" in
    --report-dir) shift_next=true ;;
    --report-dir=*) REPORT_DIR="${arg#*=}" ;;
    *)
      if [ "${shift_next:-}" = "true" ]; then
        REPORT_DIR="$arg"
        shift_next=false
      elif [ -z "$CONTRACTS_FILE" ]; then
        # First positional arg is network (already captured), second would be contracts_file
        if [ "$arg" != "$NETWORK" ]; then
          CONTRACTS_FILE="$arg"
        fi
      fi
      ;;
  esac
done

CONTRACTS_FILE="${CONTRACTS_FILE:-config/${NETWORK}_contracts.json}"

TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
REPORT_DIR="${REPORT_DIR}/${NETWORK}"
REPORT_FILE="${REPORT_DIR}/verify_$(date -u +%Y%m%dT%H%M%S).md"
LATEST_LINK="${REPORT_DIR}/LATEST.md"

mkdir -p "$REPORT_DIR"

# ── Helpers ──────────────────────────────────────────────────────────────────

TOTAL_SUITES=0
PASSED_SUITES=0
FAILED_SUITES=0
SUITE_RESULTS=()

run_suite() {
  local name="$1" script="$2"; shift 2
  local args=("$@")
  TOTAL_SUITES=$((TOTAL_SUITES + 1))

  echo "▶ Running: $name"

  local suite_output
  local suite_exit=0
  suite_output=$(bash "$script" "${args[@]}" 2>&1) || suite_exit=$?

  if [ "$suite_exit" -eq 0 ]; then
    PASSED_SUITES=$((PASSED_SUITES + 1))
    SUITE_RESULTS+=("✅ **$name** — PASSED")
  else
    FAILED_SUITES=$((FAILED_SUITES + 1))
    SUITE_RESULTS+=("❌ **$name** — FAILED (exit $suite_exit)")
  fi

  # Capture last line with summary stats
  local stats
  stats=$(echo "$suite_output" | grep -E "Results:" | tail -1 || echo "  (no summary)")
  SUITE_RESULTS+=("    $stats")

  # Store full output for the report
  echo "$suite_output"
  echo ""
}

# ── Banner ───────────────────────────────────────────────────────────────────

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Deployment Validation — StellarAid ($NETWORK)              ║"
echo "║  $(date -u '+%Y-%m-%d %H:%M:%S UTC')                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── Prerequisite checks ─────────────────────────────────────────────────────
echo "── Prerequisites ──"
for cmd in soroban; do
  if command -v "$cmd" &>/dev/null; then
    echo "  ✓ $cmd available ($(command -v "$cmd"))"
  else
    echo "  ✗ $cmd NOT found — validation may be incomplete"
  fi
done
echo "  Config: $CONTRACTS_FILE"
echo "  Report: $REPORT_FILE"
echo ""

# ── Run suites ───────────────────────────────────────────────────────────────

CONFIG_OUTPUT=$(run_suite "Configuration Loading" \
  "$SCRIPT_DIR/verify_config.sh" "$NETWORK" "$CONTRACTS_FILE" 2>&1) || true

echo ""

CONTRACT_OUTPUT=$(run_suite "Contract Function Availability" \
  "$SCRIPT_DIR/verify_contracts.sh" "$NETWORK" "$CONTRACTS_FILE" 2>&1) || true

echo ""

OPERATIONS_OUTPUT=$(run_suite "Basic Operations" \
  "$SCRIPT_DIR/verify_operations.sh" "$NETWORK" "$CONTRACTS_FILE" 2>&1) || true

echo ""

CROSS_OUTPUT=$(run_suite "Cross-Contract Calls" \
  "$SCRIPT_DIR/verify_cross_contract.sh" "$NETWORK" "$CONTRACTS_FILE" 2>&1) || true

# ── Generate Markdown report ─────────────────────────────────────────────────

{
  cat <<HEADER
# Deployment Validation Report

- **Network:** \`$NETWORK\`
- **Timestamp:** \`$TIMESTAMP\`
- **Config:** \`$CONTRACTS_FILE\`
- **Soroban version:** \$(soroban --version 2>/dev/null | head -1 || echo "unknown")

## Summary

| Suite | Status |
|-------|--------|
HEADER

  for result in "${SUITE_RESULTS[@]}"; do
    # Only include the suite name + status lines (skip stats sub-lines)
    case "$result" in
      ✅*|❌*) echo "| $result |" ;;
    esac
  done

  echo ""

  cat <<FOOTER

## Suites Run

- Configuration Loading (\`verify_config.sh\`)
- Contract Function Availability (\`verify_contracts.sh\`)
- Basic Operations (\`verify_operations.sh\`)
- Cross-Contract Calls (\`verify_cross_contract.sh\`)

## Full Output

### Configuration Loading

\`\`\`
$CONFIG_OUTPUT
\`\`\`

### Contract Function Availability

\`\`\`
$CONTRACT_OUTPUT
\`\`\`

### Basic Operations

\`\`\`
$OPERATIONS_OUTPUT
\`\`\`

### Cross-Contract Calls

\`\`\`
$CROSS_OUTPUT
\`\`\`

---
*Generated by \`verify_deployment.sh\` on $TIMESTAMP*
FOOTER
} > "$REPORT_FILE"

# Symlink latest report
ln -sf "$(basename "$REPORT_FILE")" "$LATEST_LINK"

# ── Final summary ────────────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
if [ "$FAILED_SUITES" -eq 0 ]; then
  echo "║  ✅ ALL SUITES PASSED ($PASSED_SUITES/$TOTAL_SUITES)                           ║"
else
  echo "║  ❌ $FAILED_SUITES/$TOTAL_SUITES SUITE(S) FAILED                              ║"
fi
echo "║  Report: $REPORT_FILE"
echo "╚══════════════════════════════════════════════════════════════╝"

if [ "$FAILED_SUITES" -gt 0 ]; then
  exit 1
fi
exit 0
